### ISSUE TITLE
theriak saving on the "wrong" dir

### ISSUE THREAD

**Issue by luschiro** [Theriak-Domino/pytheriak#11]
Hello!

I've been working on an [online app](https://github.com/luschiro/therlit) which uses pytheriak as the wrapper for theriak. 

I'm currently trying to run theriak from a specific dir, which is not the classic Programs, as the idea is to run it on the cloud.
The structure of the repo is the current structure that I'm working on.

I'm currently able to run theriak acessing the folder `theriak_runner`, but all the outputs are saved on the root dir, including `THERIN` and `out`. I wanted the output to be saved in the same folder where theriak is (`theriak_runner`). I reckon this is because the main .py of the app (therlit.py) is located there (?).

My question is that this config is made on pytheriak, or is intrinsic to theriak itself and I should work my way around it.

thanks in advance

**Comment by dougtinkham** [comment]
Hello luschiro

I have not used pytheriak much, but here is what I think is happening.
1. Program theriak itself would normally write its output to the directory that contains the input file THERIN, which is input to program theriak.
2. It appears that pytheriak creates this THERIN input file in the /src/pytheriak/wrapper.py method call_theriak. I am not a python expert, but it looks to create/open THERIN in whatever the current directory is according to python that is running, as the name is specified as 'THERIN'. I think pytheriak actually captures and redirects the screen output from program theriak and not the output log that program theriak writes to file. 

So, to answer your question, I think the output directory you are interested in is directly controlled by pytheriak, not theriak. Theriak should write its output to whatever directory contains the THERIN file if I remember correctly.

Doug

**Comment by luschiro** [comment]
Hey Doug, thanks for the answer.

That makes sense! Knowing that, I reckon I can work my way around where pytheriak writes THERIN (function `call_theriak`) and work from there. Thanks!
